apiVersion: v1
kind: Service
metadata:
  name: {{.Values.springApp}}
spec:
  selector:
    app: {{.Values.springApp}}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
