apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.databaseName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.databaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.databaseName }}
    spec:
      containers:
        - name: {{ .Values.databaseName }}
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.version }}"
          imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.db }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
