apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseName }}-service
spec:
  selector:
    app: {{ .Values.databaseName }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
